<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "crm_data_synchronization".
 *
 * @property integer $id
 * @property integer $clue_public_id
 * @property integer $customer_public_id
 * @property string $aliasModel
 */
abstract class CrmDataSynchronization extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'crm_data_synchronization';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['clue_public_id', 'customer_public_id'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'clue_public_id' => 'Clue Public ID',
            'customer_public_id' => 'Customer Public ID',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'id' => 'id',
            'clue_public_id' => '线索公海ID',
            'customer_public_id' => '客户公海ID',
        ]);
    }




}
